namespace HASS.Agent.Companion.Localization;

internal static partial class Strings
{
    private static readonly Dictionary<string, string> Hu = new()
    {

            // Nav
            ["Nav.General"] = "Általános",
            ["Nav.Mqtt"] = "MQTT",
            ["Nav.Capabilities"] = "Képességek",
            ["Nav.Sensors"] = "Szenzorok",
            ["Nav.Service"] = "Szolgáltatás",
            ["Nav.About"] = "Névjegy",
            ["Nav.DangerZone"] = "Veszélyes terület",

            // Bottom bar
            ["Btn.Save"] = "Mentés",
            ["Btn.Close"] = "Bezárás",
            ["Btn.Cancel"] = "Mégse",

            // General page
            ["General.Title"] = "Általános beállítások",
            ["General.Device"] = "Eszköz",
            ["General.DeviceName"] = "Eszköznév",
            ["General.BindHost"] = "Figyelési cím",
            ["General.Port"] = "Port",
            ["General.AutoStart"] = "Automatikus indítás bejelentkezéskor",
            ["General.ShowStartup"] = "Értesítés megjelenítése induláskor",
            ["General.Network"] = "Hálózat",
            ["General.CopyUrl"] = "URL másolása",
            ["General.ApiKey"] = "API kulcs",
            ["General.CopyApiKey"] = "Másolás",
            ["General.Files"] = "Fájlok",
            ["General.Settings"] = "Beállítások",
            ["General.Log"] = "Napló",
            ["General.OpenFolder"] = "Mappa megnyitása",
            ["General.Language"] = "Program nyelv",
            ["General.HaLanguage"] = "HA entitás nyelv",
            ["General.NotConfiguredError"] = "Sem az MQTT, sem a HA API nincs beállítva! Az alkalmazás jelenleg nem szolgáltat adatot! Állíts be egy MQTT (ajánlott) vagy HA API kapcsolatot.",
            ["General.MqttDisabledWarning"] = "Az MQTT nincs beállítva. Ha van MQTT brokered, érdemes azt is bekapcsolni.",
            ["General.ServiceNotInstalledWarning"] = "A Windows szolgáltatás nincs telepítve vagy nem fut, ezért a service oldali parancsok, szenzorok és a csendes frissítés nem működnek.",

            // Danger Zone page
            ["Danger.Title"] = "Veszélyes terület",
            ["Danger.Tools"] = "Eszközök",
            ["Danger.MqttMaintenance"] = "MQTT karbantartás",
            ["Danger.MqttMaintenanceHint"] = "A brokeren lévő retained HASS.Agent üzenetek listázása és törlése.",
            ["Danger.Back"] = "← Vissza",
            ["Danger.Republish"] = "Discovery újraküldése",
            ["Danger.RepublishHint"] = "Az eszköz discovery újraküldése az aktív kapcsolaton (MQTT vagy HA API).",
            ["Danger.RepublishDone"] = "Discovery újraküldve.",
            ["Danger.RepublishNotConnected"] = "Nincs aktív kapcsolat — a discovery-t nem sikerült elküldeni.",
            ["Danger.DebugLog"] = "Debug napló",
            ["Danger.DebugLogHint"] = "Élő napló nézegető szűréssel és bőbeszédű (DEBUG) naplózás kapcsolóval.",
            ["Danger.DebugVerbose"] = "Bőbeszédű naplózás (DEBUG szint, az app újraindításáig)",
            ["Danger.DebugFilter"] = "Szűrő...",
            ["Danger.Monitor"] = "Élő MQTT monitor",
            ["Danger.MonitorHint"] = "A hass.agent topicok figyelése valós időben — mit küld és kap az agent.",
            ["Danger.MonitorStart"] = "Indítás",
            ["Danger.MonitorStop"] = "Leállítás",
            ["Danger.ColTime"] = "Idő",
            ["Danger.ColRetain"] = "R",
            ["Danger.Backup"] = "Mentés / visszaállítás",
            ["Danger.BackupHint"] = "Beállítások exportálása JSON fájlba, vagy visszaállítás fájlból.",
            ["Danger.BackupNote"] = "Az export nem tartalmazza az MQTT jelszót és a HA API tokent — importálás után újra meg kell adni őket.",
            ["Danger.Export"] = "Beállítások exportálása",
            ["Danger.Import"] = "Beállítások importálása",
            ["Danger.ExportDone"] = "Beállítások exportálva:\n{0}",
            ["Danger.ImportConfirm"] = "Az importálás felülírja a jelenlegi beállításokat és újraindítja az alkalmazást.\n\nFolytatod?",
            ["Danger.ImportDone"] = "Beállítások importálva. Az alkalmazás most újraindul.",
            ["Danger.FactoryReset"] = "Gyári visszaállítás",
            ["Danger.FactoryResetHint"] = "Az összes beállítás törlése (új serial number és API kulcs) és az alkalmazás újraindítása.",
            ["Danger.FactoryConfirm1"] = "Ez MINDEN beállítást töröl, beleértve az MQTT/HA API kapcsolatot, az API kulcsot és a serial numbert.\n\nAz eszköz ÚJ eszközként fog megjelenni a Home Assistantban. Folytatod?",
            ["Danger.FactoryConfirm2"] = "Biztosan biztos vagy benne? Ez nem visszavonható.",
            ["Danger.BetaUpdates"] = "Beta frissítések — a frissítéskeresés a pre-release kiadásokat is felajánlja",

            // HA persistent notifications (HA entitás nyelv)
            ["HaPn.UpdateTitle"] = "HASS.Agent frissítés",
            ["HaPn.UpdateCompleted"] = "{0}: frissítve {1} → {2}.",
            ["HaPn.NoUpdate"] = "{0}: nincs elérhető frissítés.",
            ["HaPn.NoInstaller"] = "{0}: a(z) {1} kiadáshoz nincs telepítő — telepítsd kézzel.",
            ["HaPn.UpdateStartedSilent"] = "{0}: a(z) {1} frissítés csendes telepítése elindult a rendszerszolgáltatáson keresztül.",
            ["HaPn.UpdateStartedUac"] = "{0}: a(z) {1} frissítés elindult — erősítsd meg a UAC ablakot a gépen. Teljesen csendes frissítéshez telepítsd a rendszerszolgáltatást.",
            ["HaPn.UpdateStartedServiceStopped"] = "{0}: a rendszerszolgáltatás telepítve van, de áll, ezért a(z) {1} frissítéshez UAC megerősítés kell a gépen. Indítsd el a szolgáltatást (tray → Szolgáltatás → Indítás) a teljesen csendes frissítéshez.",
            ["HaPn.UpdateFailed"] = "{0}: a frissítés sikertelen: {1}",
            ["Danger.Warning"] = "Élő eszköz retained üzeneteinek törlése után annak entitásai eltűnnek a Home Assistantból, amíg az eszköz újra nem publikálja a discovery-t (újraindítás vagy újracsatlakozás).",
            ["Danger.RetainedCard"] = "Retained MQTT üzenetek",
            ["Danger.LoadOwn"] = "Ezen eszköz üzenetei",
            ["Danger.LoadAll"] = "Összes HASS.Agent üzenet",
            ["Danger.Loading"] = "Broker átvizsgálása...",
            ["Danger.NoMessages"] = "Nem található retained üzenet.",
            ["Danger.Found"] = "{0} retained üzenet található.",
            ["Danger.ColTopic"] = "Topic",
            ["Danger.ColSize"] = "Méret",
            ["Danger.ColDevice"] = "Eszköz",
            ["Danger.ThisDevice"] = "ez az eszköz",
            ["Danger.OtherDevice"] = "másik",
            ["Danger.SelectAll"] = "Összes kijelölése",
            ["Danger.DeleteSelected"] = "Kijelöltek törlése",
            ["Danger.ConfirmDelete"] = "Törlöd a kijelölt {0} retained üzenetet a brokerről?\n\nÉlő eszközök entitásai eltűnnek a Home Assistantból, amíg újra nem publikálják a discovery-t.",
            ["Danger.Deleted"] = "{0} retained üzenet törölve.",
            ["Danger.MqttRequired"] = "A funkció használatához az MQTT-nek beállítva és engedélyezve kell lennie.",
            ["Danger.Error"] = "A művelet sikertelen: {0}",

            // MQTT page
            ["Mqtt.Title"] = "MQTT beállítások",
            ["Mqtt.Connection"] = "Kapcsolat",
            ["Mqtt.Enable"] = "MQTT engedélyezése",
            ["Mqtt.BrokerHost"] = "Broker cím",
            ["Mqtt.Port"] = "Port",
            ["Mqtt.Username"] = "Felhasználónév",
            ["Mqtt.Password"] = "Jelszó",
            ["Mqtt.UseTls"] = "TLS használata",
            ["Mqtt.RetainDiscovery"] = "Discovery retain flag",
            ["Mqtt.Notifications"] = "Értesítések MQTT-n",
            ["Mqtt.MediaPlayer"] = "Médialejátszó MQTT-n",
            ["Mqtt.ButtonsByRoles"] = "Gombok MQTT-n (szerepkörök alapján)",
            ["Mqtt.SystemSensors"] = "Gépállapot szenzorok MQTT-n",
            ["Mqtt.HostRequired"] = "A broker cím nem lehet üres.",
            ["Mqtt.NotConfigured"] = "Az MQTT nincs beállítva.",
            ["Mqtt.TestButton"] = "Kapcsolat tesztelése",
            ["Mqtt.TestSuccess"] = "Sikeres kapcsolódás a brokerhez.",
            ["Mqtt.TestFailed"] = "Kapcsolódás sikertelen: {0}",
            ["Mqtt.TestTimeout"] = "időtúllépés",

            // HA API page
            ["Nav.HaApi"] = "HA API",
            ["HaApi.Title"] = "HA API beállítások",
            ["HaApi.Connection"] = "Kapcsolat",
            ["HaApi.Enable"] = "HA API engedélyezése (failover MQTT kieséskor)",
            ["HaApi.Url"] = "Home Assistant URL",
            ["HaApi.Token"] = "Hosszú élettartamú hozzáférési token",
            ["HaApi.HttpWarning"] = "A HTTP nem titkosított! Csak helyi hálózaton ajánlott!",
            ["HaApi.TestButton"] = "Kapcsolat tesztelése",
            ["HaApi.TestSuccess"] = "Csatlakozva: Home Assistant {0}\nHASS.Agent integráció {1}",
            ["HaApi.TestIntegrationMissing"] = "Csatlakozva: Home Assistant {0}\nA HASS.Agent integráció verziója nem ismert! Szükséges: {1}+.",
            ["HaApi.TestIntegrationOld"] = "Csatlakozva: Home Assistant {0},\nA HASS.Agent integráció {1} túl régi! Szükséges: {2}+.",
            ["HaApi.TestIntegrationCheckFailed"] = "Csatlakozva: Home Assistant {0}\nAz integráció verzióellenőrzése sikertelen: {1}",
            ["HaApi.TestFailed"] = "Kapcsolat sikertelen: {0}",
            ["HaApi.UrlRequired"] = "A Home Assistant URL nem lehet üres.",
            ["HaApi.Description"] = "Távoli kapcsolat a Home Assistanttal WebSocket API-n keresztül.",
            ["HaApi.Limitations"] = "MQTT-hez képest: nincs retain (újraindításkor az állapot elvész amíg az agent újra nem csatlakozik), nincs Last Will (nincs automatikus offline érzékelés), a thumbnail ~33%-kal nagyobb (base64). Távoli elérésnél HTTPS kötelező (pl. Nabu Casa).",
            ["HaApi.DisabledWarning"] = "A HA API nincs bekapcsolva, a gép távolról nem lesz elérhető.",

            // Capabilities page
            ["Cap.Title"] = "Képességek",
            ["Cap.Functions"] = "Funkciók",
            ["Cap.Notifications"] = "Értesítések (tray app)",
            ["Cap.MediaPlayer"] = "Médialejátszó (tray app)",
            ["Cap.SensorsService"] = "Rendszerszenzorok (szolgáltatás)",
            ["Cap.SensorsApp"] = "Rendszerszenzorok (tray app)",
            ["Cap.SensorInterval"] = "Szenzor frissítés",
            ["Cap.FastSensorInterval"] = "Gyors szenzorok",
            ["Cap.NormalSensorInterval"] = "Normál szenzorok",
            ["Cap.HourlySensorInterval"] = "Órás szenzorok",
            ["Cap.Seconds"] = "mp",
            ["Cap.Commands"] = "Rendszerparancsok",
            ["Cap.CustomCommands"] = "Egyéni parancsok",
            ["Cap.CustomCommandsHelp"] = "Saját programok vagy PowerShell szkriptek futtatása. Itt te határozod meg, mi fusson; a Home Assistant csak név alapján indítja — tetszőleges parancsot nem küldhet.",
            ["Cap.CustomCommandNew"] = "Új parancs",
            ["Cap.CommandColumn"] = "Parancs / szkript",
            ["Cap.ArgumentsColumn"] = "Argumentumok",
            ["CmdType.process"] = "Program",
            ["CmdType.powershell"] = "PowerShell",
            ["CmdType.pwsh"] = "PowerShell 7 (pwsh)",
            ["Cap.WindowTitle"] = "képességek",
            ["Cap.Heading"] = "Mi kezelje és mit hirdessen a Home Assistant felé?",
            ["Cap.What"] = "Mi",
            ["Cap.NotificationsShort"] = "Értesítések",
            ["Cap.MediaPlayerShort"] = "Médialejátszó",
            ["Cap.SystemSensorsShort"] = "Gépállapot szenzorok",
            ["Cap.ServiceReloadHint"] = "A service pipák mentése után a futó service automatikusan újratölti a beállításokat. Üres service cella = jelenleg nem service-kompatibilis.",

            // Sensors page
            ["Sensors.Title"] = "Szenzorok",
            ["Sensors.BuiltIn"] = "Beépített szenzorok",
            ["Sensors.Custom"] = "Egyedi szenzorok",
            ["Sensors.Sensor"] = "Szenzor",
            ["Sensors.Active"] = "Aktív",
            ["Sensors.Type"] = "Típus",
            ["Sensors.Name"] = "Név",
            ["Sensors.Parameter"] = "Paraméter",
            ["Sensors.Unit"] = "M.egys.",
            ["Sensors.Profile"] = "Profil",
            ["Sensors.Value"] = "Érték",
            ["Sensors.Add"] = "Hozzáadás",
            ["Sensors.Remove"] = "Törlés",
            ["Sensors.TestValue"] = "Teszt",
            ["Sensors.NewSensor"] = "Új szenzor",
            ["Sensors.WindowTitle"] = "szenzorok",
            ["Sensors.Basic"] = "Alap szenzorok",
            ["Sensors.CustomAdd"] = "Egyedi hozzáadás",
            ["Sensors.CustomRemove"] = "Egyedi törlés",
            ["Sensors.MultiValueTooltip"] = "Ez a szenzor több értéket is ad. Kattints egy attribútum alapú egyedi szenzor hozzáadásához.",
            ["Sensors.AttributeSensorName"] = "{0}: {1}",
            ["Sensors.CustomHelp"] = "Paraméterek: process_running = processz név, service_status = Windows service név, disk_free = meghajtó betűjel/útvonal. Parancs típusok = a program/parancssor (pl. nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits); a kimenet első sora lesz az érték — használd a Normál/Óránkénti profilt. Beépített attribútumhoz kattints a + ikonra; minden elérhető attribútum bekerül, listáknál [0] indexszel.",
            ["Sensors.ValueLoading"] = "olvasás...",
            ["Sensors.ValueNotTested"] = "nincs tesztelve",
            ["Sensors.ValueMissingParameter"] = "hiányzó paraméter",
            ["Sensors.ValueError"] = "hiba: {0}",

            ["PollingProfile.fast"] = "Gyors",
            ["PollingProfile.normal"] = "Normál",
            ["PollingProfile.hourly"] = "Órás",
            ["PollingProfile.startup"] = "Indításkor",
            ["PollingProfile.push"] = "Push",

            // Service page
            ["Service.Title"] = "Szolgáltatás",
            ["Service.Status"] = "Állapot",
            ["Service.Refresh"] = "Frissítés",
            ["Service.Actions"] = "Műveletek",
            ["Service.Install"] = "Telepítés / frissítés",
            ["Service.Start"] = "Indítás",
            ["Service.Stop"] = "Leállítás",
            ["Service.Uninstall"] = "Eltávolítás",
            ["Service.ConfirmUninstall"] = "Biztosan eltávolítod a szolgáltatást?",

            // About page
            ["About.Version"] = "Verzió",
            ["About.Developer"] = "Fejlesztő",
            ["About.Description"] = "Modern .NET 10 Windows kliens a Home Assistant integrációhoz.",
            ["About.ReportIssue"] = "Hibabejelentés",
            ["About.CheckUpdates"] = "Frissítés keresése",
            ["About.CheckingUpdates"] = "Ellenőrzés...",
            ["About.DownloadingUpdate"] = "Letöltés...",
            ["About.NoUpdates"] = "Naprakész verziót használsz. Legfrissebb release: {0}.",
            ["About.UpdateAvailable"] = "Elérhető egy újabb release: {0}\n\nTelepített verzió: {1}\n\nLetöltöd most?",
            ["About.UpdateDownloaded"] = "A frissítés letöltve ide:\n{0}\n\nMegnyitod most?",
            ["About.UpdateCheckFailed"] = "Nem sikerült lekérni a legfrissebb GitHub release-t.",
            ["About.UpdateError"] = "Frissítés ellenőrzési hiba: {0}",

            // Messages
            ["Msg.SettingsSaved"] = "Beállítások mentve.",
            ["Msg.RestartRequired"] = "A nyelv megváltoztatásához indítsd újra az alkalmazást.",
            ["Msg.NotConfigured"] = "Sem az MQTT, sem a HA API nincs beállítva. Kattints ide a beállításhoz.",

            // Tray
            ["Tray.Open"] = "Megnyitás",
            ["Tray.Service"] = "Rendszerszolgáltatás",
            ["Tray.CopyUrl"] = "URL másolása",
            ["Tray.Exit"] = "Kilépés",
            ["Tray.ServiceCommand"] = "System service parancs elindítva.",
            ["Tray.ServiceStatus"] = "Status",
            ["Tray.ServiceInstall"] = "Telepítés / frissítés",
            ["Tray.ServiceStart"] = "Indítás",
            ["Tray.ServiceStop"] = "Leállítás",
            ["Tray.ServiceUninstall"] = "Eltávolítás",

            // Service manager
            ["SvcMgr.Installed"] = "Telepítve",
            ["SvcMgr.Yes"] = "igen",
            ["SvcMgr.No"] = "nem",
            ["SvcMgr.Status"] = "Állapot",
            ["SvcMgr.StartType"] = "Indítás",
            ["SvcMgr.NotInstalled"] = "A service nincs telepítve.",
            ["SvcMgr.StatusError"] = "Service status hiba: {0}",
            ["SvcMgr.Unknown"] = "ismeretlen",
            ["SvcMgr.OsRequired"] = "A {0} telepítéséhez Windows 10 2004 (build 19041) vagy újabb rendszer szükséges. Windows 11 ajánlott.",
            ["SvcMgr.UnknownCommand"] = "Ismeretlen service parancs: {0}",
            ["SvcMgr.DeletePending"] = "A régi service még törlés alatt áll. Várj pár másodpercet, majd próbáld újra.",
            ["SvcMgr.InstalledNotStarted"] = "A service települt, de nem indult el.",
            ["SvcMgr.InstalledAndStarted"] = "A {0} telepítve és elindítva.",
            ["SvcMgr.ScFailed"] = "Nem sikerült elindítani az sc.exe-t.",

            // System commands
            ["Cmd.lock"] = "Gép zárolása",
            ["Cmd.sleep"] = "Alvás",
            ["Cmd.monitor_off"] = "Monitor kikapcsolása",
            ["Cmd.volume_up"] = "Hangerő fel",
            ["Cmd.volume_down"] = "Hangerő le",
            ["Cmd.toggle_mute"] = "Némítás váltása",
            ["Cmd.shutdown"] = "Leállítás",
            ["Cmd.restart"] = "Újraindítás",
            ["Cmd.restart_cancel"] = "Leállítás/újraindítás megszakítása",
            ["Cmd.shutdown_comment"] = "Home Assistantból leállítva",
            ["Cmd.restart_comment"] = "Home Assistantból újraindítva",

            // Built-in sensors
            ["Sensor.cpu_usage"] = "CPU terhelés",
            ["Sensor.memory_usage"] = "Memória használat",
            ["Sensor.memory_available_mb"] = "Szabad memória",
            ["Sensor.system_drive_free_percent"] = "Rendszermeghajtó szabad %",
            ["Sensor.system_drive_free_gb"] = "Rendszermeghajtó szabad hely",
            ["Sensor.uptime_seconds"] = "Uptime",
            ["Sensor.battery_level"] = "Akkumulátor",
            ["Sensor.power_status"] = "Tápellátás",
            ["Sensor.network_address"] = "LAN IP",
            ["Sensor.session_state"] = "Munkamenet állapot",
            ["Sensor.logged_in_user"] = "Bejelentkezett felhasználó",
            ["Sensor.pending_reboot"] = "Újraindítás szükséges",
            ["Sensor.boot_time"] = "Boot idő",
            ["Sensor.battery_time_remaining"] = "Akkumulátor hátralévő idő",
            ["Sensor.vpn_connected"] = "VPN csatlakozva",
            ["Sensor.wifi_ssid"] = "Wi-Fi SSID",
            ["Sensor.wifi_signal"] = "Wi-Fi jelerősség",
            ["Sensor.logged_in_users"] = "Bejelentkezett felhasználók",
            ["Sensor.rdp_sessions"] = "RDP munkamenetek",
            ["Sensor.bluetooth_enabled"] = "Bluetooth engedélyezve",
            ["Sensor.windows_update_pending"] = "Windows Update függőben",
            ["Sensor.event_log_errors_recent"] = "Friss eseménynapló hibák",
            ["Sensor.last_shutdown_reason"] = "Utolsó leállítás oka",
            ["Sensor.active_window"] = "Aktív ablak",
            ["Sensor.active_process"] = "Aktív processz",
            ["Sensor.foreground_app_title"] = "Aktív alkalmazás és ablak",
            ["Sensor.volume"] = "Hangerő",
            ["Sensor.muted"] = "Némítva",
            ["Sensor.monitor_power_state"] = "Monitor állapot",
            ["Sensor.active_display"] = "Aktív kijelzők",
            ["Sensor.idle_time_seconds"] = "Inaktív idő",
            ["Sensor.session_locked"] = "Munkamenet zárolva",
            ["Sensor.user_present"] = "Felhasználó jelen van",
            ["Sensor.clipboard_text_available"] = "Vágólapon szöveg",
            ["Sensor.audio_output_device"] = "Audio kimenet",
            ["Sensor.microphone_muted"] = "Mikrofon némítva",

            // Custom sensor types
            ["SensorType.process_running"] = "Futó folyamat",
            ["SensorType.service_status"] = "Szolgáltatás állapot",
            ["SensorType.disk_free"] = "Szabad lemezterület",
            ["SensorType.built_in_attribute"] = "Beépített attribútum",
            ["SensorType.command"] = "Parancs (program)",
            ["SensorType.command_powershell"] = "Parancs (PowerShell)",
            ["SensorType.command_pwsh"] = "Parancs (PowerShell 7)",
    };
}
