namespace HASS.Agent.Companion.Localization;

internal static partial class Strings
{
    private static readonly Dictionary<string, string> En = new()
    {

            // Nav
            ["Nav.General"] = "General",
            ["Nav.Mqtt"] = "MQTT",
            ["Nav.Capabilities"] = "Capabilities",
            ["Nav.Sensors"] = "Sensors",
            ["Nav.Service"] = "Service",
            ["Nav.About"] = "About",
            ["Nav.DangerZone"] = "Danger Zone",

            // Bottom bar
            ["Btn.Save"] = "Save",
            ["Btn.Close"] = "Close",
            ["Btn.Cancel"] = "Cancel",

            // General page
            ["General.Title"] = "General settings",
            ["General.Device"] = "Device",
            ["General.DeviceName"] = "Device name",
            ["General.BindHost"] = "Bind address",
            ["General.Port"] = "Port",
            ["General.AutoStart"] = "Start automatically on login",
            ["General.ShowStartup"] = "Show notification on startup",
            ["General.Network"] = "Network",
            ["General.CopyUrl"] = "Copy URL",
            ["General.ApiKey"] = "API key",
            ["General.CopyApiKey"] = "Copy key",
            ["General.Files"] = "Files",
            ["General.Settings"] = "Settings",
            ["General.Log"] = "Log",
            ["General.OpenFolder"] = "Open folder",
            ["General.Language"] = "UI language",
            ["General.HaLanguage"] = "HA entity language",
            ["General.NotConfiguredError"] = "Neither MQTT nor HA API is configured — the application is not sending any data. Set up an MQTT (recommended) or HA API connection.",
            ["General.MqttDisabledWarning"] = "MQTT is not configured. If you have an MQTT broker, consider enabling it.",
            ["General.ServiceNotInstalledWarning"] = "The Windows service is not installed or not running, so service-side commands, sensors, and silent updates will not work.",

            // Danger Zone page
            ["Danger.Title"] = "Danger Zone",
            ["Danger.Tools"] = "Tools",
            ["Danger.MqttMaintenance"] = "MQTT maintenance",
            ["Danger.MqttMaintenanceHint"] = "List and delete retained HASS.Agent messages on the broker.",
            ["Danger.Back"] = "← Back",
            ["Danger.Republish"] = "Republish discovery",
            ["Danger.RepublishHint"] = "Re-send the device discovery on the active connection (MQTT or HA API).",
            ["Danger.RepublishDone"] = "Discovery republished.",
            ["Danger.RepublishNotConnected"] = "No active connection — discovery could not be sent.",
            ["Danger.DebugLog"] = "Debug log",
            ["Danger.DebugLogHint"] = "Live log viewer with filtering and verbose (DEBUG) logging toggle.",
            ["Danger.DebugVerbose"] = "Verbose logging (DEBUG level, until app restart)",
            ["Danger.DebugFilter"] = "Filter...",
            ["Danger.Monitor"] = "Live MQTT monitor",
            ["Danger.MonitorHint"] = "Watch hass.agent topics in real time — what the agent sends and receives.",
            ["Danger.MonitorStart"] = "Start",
            ["Danger.MonitorStop"] = "Stop",
            ["Danger.ColTime"] = "Time",
            ["Danger.ColRetain"] = "R",
            ["Danger.Backup"] = "Backup / restore",
            ["Danger.BackupHint"] = "Export settings to a JSON file, or restore them from one.",
            ["Danger.BackupNote"] = "The export does not contain the MQTT password and the HA API token — those must be re-entered after import.",
            ["Danger.Export"] = "Export settings",
            ["Danger.Import"] = "Import settings",
            ["Danger.ExportDone"] = "Settings exported to:\n{0}",
            ["Danger.ImportConfirm"] = "Importing replaces the current settings and restarts the application.\n\nContinue?",
            ["Danger.ImportDone"] = "Settings imported. The application will now restart.",
            ["Danger.FactoryReset"] = "Factory reset",
            ["Danger.FactoryResetHint"] = "Delete all settings (new serial number and API key) and restart the application.",
            ["Danger.FactoryConfirm1"] = "This deletes ALL settings, including the MQTT/HA API connection, the API key, and the serial number.\n\nThe device will appear as a NEW device in Home Assistant. Continue?",
            ["Danger.FactoryConfirm2"] = "Are you absolutely sure? This cannot be undone.",
            ["Danger.BetaUpdates"] = "Beta updates — update checks also offer pre-releases",

            // HA persistent notifications (HA entity language)
            ["HaPn.UpdateTitle"] = "HASS.Agent update",
            ["HaPn.UpdateCompleted"] = "{0}: updated from {1} to {2}.",
            ["HaPn.NoUpdate"] = "{0}: no update available.",
            ["HaPn.NoInstaller"] = "{0}: release {1} has no installer asset — install it manually.",
            ["HaPn.UpdateStartedSilent"] = "{0}: installing update {1} silently via the system service.",
            ["HaPn.UpdateStartedUac"] = "{0}: update {1} started — confirm the UAC prompt on the PC. Install the system service for fully silent updates.",
            ["HaPn.UpdateStartedServiceStopped"] = "{0}: the system service is installed but stopped, so update {1} needs a UAC prompt on the PC. Start the service (tray → Service → Start) for fully silent updates.",
            ["HaPn.UpdateFailed"] = "{0}: update failed: {1}",
            ["Danger.Warning"] = "Deleting retained messages of a live device removes its entities from Home Assistant until that device publishes its discovery again (restart or reconnect).",
            ["Danger.RetainedCard"] = "Retained MQTT messages",
            ["Danger.LoadOwn"] = "Load this device's messages",
            ["Danger.LoadAll"] = "Load all HASS.Agent messages",
            ["Danger.Loading"] = "Scanning broker...",
            ["Danger.NoMessages"] = "No retained messages found.",
            ["Danger.Found"] = "{0} retained message(s) found.",
            ["Danger.ColTopic"] = "Topic",
            ["Danger.ColSize"] = "Size",
            ["Danger.ColDevice"] = "Device",
            ["Danger.ThisDevice"] = "this device",
            ["Danger.OtherDevice"] = "other",
            ["Danger.SelectAll"] = "Select all",
            ["Danger.DeleteSelected"] = "Delete selected",
            ["Danger.ConfirmDelete"] = "Delete {0} retained message(s) from the broker?\n\nEntities of live devices will disappear from Home Assistant until those devices publish their discovery again.",
            ["Danger.Deleted"] = "{0} retained message(s) deleted.",
            ["Danger.MqttRequired"] = "MQTT must be configured and enabled to use this feature.",
            ["Danger.Error"] = "Operation failed: {0}",

            // MQTT page
            ["Mqtt.Title"] = "MQTT settings",
            ["Mqtt.Connection"] = "Connection",
            ["Mqtt.Enable"] = "Enable MQTT",
            ["Mqtt.BrokerHost"] = "Broker address",
            ["Mqtt.Port"] = "Port",
            ["Mqtt.Username"] = "Username",
            ["Mqtt.Password"] = "Password",
            ["Mqtt.UseTls"] = "Use TLS",
            ["Mqtt.RetainDiscovery"] = "Discovery retain flag",
            ["Mqtt.Notifications"] = "Notifications over MQTT",
            ["Mqtt.MediaPlayer"] = "Media player over MQTT",
            ["Mqtt.ButtonsByRoles"] = "Buttons over MQTT (based on roles)",
            ["Mqtt.SystemSensors"] = "System sensors over MQTT",
            ["Mqtt.HostRequired"] = "Broker address cannot be empty.",
            ["Mqtt.NotConfigured"] = "MQTT is not configured.",
            ["Mqtt.TestButton"] = "Test connection",
            ["Mqtt.TestSuccess"] = "Connected to the broker.",
            ["Mqtt.TestFailed"] = "Connection failed: {0}",
            ["Mqtt.TestTimeout"] = "timeout",

            // HA API page
            ["Nav.HaApi"] = "HA API",
            ["HaApi.Title"] = "HA API settings",
            ["HaApi.Connection"] = "Connection",
            ["HaApi.Enable"] = "Enable HA API (failover when MQTT unavailable)",
            ["HaApi.Url"] = "Home Assistant URL",
            ["HaApi.Token"] = "Long-lived access token",
            ["HaApi.HttpWarning"] = "HTTP is not encrypted — only recommended on local network!",
            ["HaApi.TestButton"] = "Test connection",
            ["HaApi.TestSuccess"] = "Connected: Home Assistant {0}, HASS.Agent integration {1}",
            ["HaApi.TestIntegrationMissing"] = "Connected: Home Assistant {0}, but HASS.Agent integration version is unknown. Required: {1}+.",
            ["HaApi.TestIntegrationOld"] = "Connected: Home Assistant {0}, but HASS.Agent integration {1} is too old. Required: {2}+.",
            ["HaApi.TestIntegrationCheckFailed"] = "Connected: Home Assistant {0}, but integration version check failed: {1}",
            ["HaApi.TestFailed"] = "Connection failed: {0}",
            ["HaApi.UrlRequired"] = "Home Assistant URL cannot be empty.",
            ["HaApi.Description"] = "Remote connection to Home Assistant via WebSocket API.",
            ["HaApi.Limitations"] = "Compared to MQTT: no retain (state is lost on restart until agent reconnects), no Last Will (no automatic offline detection), thumbnails are ~33% larger (base64). HTTPS is required for remote access (e.g. Nabu Casa).",
            ["HaApi.DisabledWarning"] = "HA API is not enabled — the device will not be reachable remotely.",

            // Capabilities page
            ["Cap.Title"] = "Capabilities",
            ["Cap.Functions"] = "Functions",
            ["Cap.Notifications"] = "Notifications (tray app)",
            ["Cap.MediaPlayer"] = "Media player (tray app)",
            ["Cap.SensorsService"] = "System sensors — service",
            ["Cap.SensorsApp"] = "System sensors — tray app",
            ["Cap.SensorInterval"] = "Sensor interval",
            ["Cap.FastSensorInterval"] = "Fast sensors",
            ["Cap.NormalSensorInterval"] = "Normal sensors",
            ["Cap.HourlySensorInterval"] = "Hourly sensors",
            ["Cap.Seconds"] = "s",
            ["Cap.Commands"] = "System commands",
            ["Cap.CustomCommands"] = "Custom commands",
            ["Cap.CustomCommandsHelp"] = "Run your own programs or PowerShell scripts. You define what runs here; Home Assistant only triggers it by name — it cannot send arbitrary commands.",
            ["Cap.CustomCommandNew"] = "New command",
            ["Cap.CommandColumn"] = "Command / script",
            ["Cap.ArgumentsColumn"] = "Arguments",
            ["CmdType.process"] = "Program",
            ["CmdType.powershell"] = "PowerShell",
            ["CmdType.pwsh"] = "PowerShell 7 (pwsh)",
            ["Cap.WindowTitle"] = "capabilities",
            ["Cap.Heading"] = "What should handle and advertise features to Home Assistant?",
            ["Cap.What"] = "Feature",
            ["Cap.NotificationsShort"] = "Notifications",
            ["Cap.MediaPlayerShort"] = "Media player",
            ["Cap.SystemSensorsShort"] = "System sensors",
            ["Cap.ServiceReloadHint"] = "After saving service checkboxes, the running service automatically reloads settings. Empty service cell = currently not service-compatible.",

            // Sensors page
            ["Sensors.Title"] = "Sensors",
            ["Sensors.BuiltIn"] = "Built-in sensors",
            ["Sensors.Custom"] = "Custom sensors",
            ["Sensors.Sensor"] = "Sensor",
            ["Sensors.Active"] = "Active",
            ["Sensors.Type"] = "Type",
            ["Sensors.Name"] = "Name",
            ["Sensors.Parameter"] = "Parameter",
            ["Sensors.Unit"] = "Unit",
            ["Sensors.Profile"] = "Profile",
            ["Sensors.Value"] = "Value",
            ["Sensors.Add"] = "Add",
            ["Sensors.Remove"] = "Remove",
            ["Sensors.TestValue"] = "Test",
            ["Sensors.NewSensor"] = "New sensor",
            ["Sensors.WindowTitle"] = "sensors",
            ["Sensors.Basic"] = "Built-in sensors",
            ["Sensors.CustomAdd"] = "Add custom",
            ["Sensors.CustomRemove"] = "Remove custom",
            ["Sensors.MultiValueTooltip"] = "This sensor has additional values. Click to add a custom sensor from an attribute.",
            ["Sensors.AttributeSensorName"] = "{0}: {1}",
            ["Sensors.CustomHelp"] = "Parameters: process_running = process name, service_status = Windows service name, disk_free = drive letter/path. Command types = the program/command line (e.g. nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits); the first non-empty line of its output becomes the value — use the Normal/Hourly profile. For built-in attributes, click + on a built-in sensor; every available attribute is added with [0] for list values.",
            ["Sensors.ValueLoading"] = "reading...",
            ["Sensors.ValueNotTested"] = "not tested",
            ["Sensors.ValueMissingParameter"] = "missing parameter",
            ["Sensors.ValueError"] = "error: {0}",

            ["PollingProfile.fast"] = "Fast",
            ["PollingProfile.normal"] = "Normal",
            ["PollingProfile.hourly"] = "Hourly",
            ["PollingProfile.startup"] = "Startup",
            ["PollingProfile.push"] = "Push",

            // Service page
            ["Service.Title"] = "Service",
            ["Service.Status"] = "Status",
            ["Service.Refresh"] = "Refresh",
            ["Service.Actions"] = "Actions",
            ["Service.Install"] = "Install / update",
            ["Service.Start"] = "Start",
            ["Service.Stop"] = "Stop",
            ["Service.Uninstall"] = "Uninstall",
            ["Service.ConfirmUninstall"] = "Are you sure you want to uninstall the service?",

            // About page
            ["About.Version"] = "Version",
            ["About.Developer"] = "Developer",
            ["About.Description"] = "Modern .NET 10 Windows client for Home Assistant integration.",
            ["About.ReportIssue"] = "Report issue",
            ["About.CheckUpdates"] = "Check updates",
            ["About.CheckingUpdates"] = "Checking...",
            ["About.DownloadingUpdate"] = "Downloading...",
            ["About.NoUpdates"] = "You are up to date. Latest release: {0}.",
            ["About.UpdateAvailable"] = "A newer release is available: {0}\n\nInstalled version: {1}\n\nDownload it now?",
            ["About.UpdateDownloaded"] = "Update downloaded to:\n{0}\n\nOpen it now?",
            ["About.UpdateCheckFailed"] = "Unable to read the latest release from GitHub.",
            ["About.UpdateError"] = "Update check failed: {0}",

            // Messages
            ["Msg.SettingsSaved"] = "Settings saved.",
            ["Msg.RestartRequired"] = "Please restart the application to apply the language change.",
            ["Msg.NotConfigured"] = "Neither MQTT nor HA API is configured. Click here to set up.",

            // Tray
            ["Tray.Open"] = "Open",
            ["Tray.Service"] = "System service",
            ["Tray.CopyUrl"] = "Copy URL",
            ["Tray.Exit"] = "Exit",
            ["Tray.ServiceCommand"] = "System service command started.",
            ["Tray.ServiceStatus"] = "Status",
            ["Tray.ServiceInstall"] = "Install / update",
            ["Tray.ServiceStart"] = "Start",
            ["Tray.ServiceStop"] = "Stop",
            ["Tray.ServiceUninstall"] = "Uninstall",

            // System commands
            // Service manager
            ["SvcMgr.Installed"] = "Installed",
            ["SvcMgr.Yes"] = "yes",
            ["SvcMgr.No"] = "no",
            ["SvcMgr.Status"] = "Status",
            ["SvcMgr.StartType"] = "Start type",
            ["SvcMgr.NotInstalled"] = "Service is not installed.",
            ["SvcMgr.StatusError"] = "Service status error: {0}",
            ["SvcMgr.Unknown"] = "unknown",
            ["SvcMgr.OsRequired"] = "{0} requires Windows 10 2004 (build 19041) or newer. Windows 11 is recommended.",
            ["SvcMgr.UnknownCommand"] = "Unknown service command: {0}",
            ["SvcMgr.DeletePending"] = "The old service is still being deleted. Wait a few seconds and try again.",
            ["SvcMgr.InstalledNotStarted"] = "Service installed but did not start.",
            ["SvcMgr.InstalledAndStarted"] = "{0} installed and started.",
            ["SvcMgr.ScFailed"] = "Failed to start sc.exe.",

            ["Cmd.lock"] = "Lock computer",
            ["Cmd.sleep"] = "Sleep",
            ["Cmd.monitor_off"] = "Turn off monitor",
            ["Cmd.volume_up"] = "Volume up",
            ["Cmd.volume_down"] = "Volume down",
            ["Cmd.toggle_mute"] = "Toggle mute",
            ["Cmd.shutdown"] = "Shutdown",
            ["Cmd.restart"] = "Restart",
            ["Cmd.restart_cancel"] = "Cancel shutdown/restart",
            ["Cmd.shutdown_comment"] = "Shut down from Home Assistant",
            ["Cmd.restart_comment"] = "Restarted from Home Assistant",

            // Built-in sensors
            ["Sensor.cpu_usage"] = "CPU usage",
            ["Sensor.memory_usage"] = "Memory usage",
            ["Sensor.memory_available_mb"] = "Available memory",
            ["Sensor.system_drive_free_percent"] = "System drive free %",
            ["Sensor.system_drive_free_gb"] = "System drive free space",
            ["Sensor.uptime_seconds"] = "Uptime",
            ["Sensor.battery_level"] = "Battery level",
            ["Sensor.power_status"] = "Power status",
            ["Sensor.network_address"] = "LAN IP",
            ["Sensor.session_state"] = "Session state",
            ["Sensor.logged_in_user"] = "Logged in user",
            ["Sensor.pending_reboot"] = "Pending reboot",
            ["Sensor.boot_time"] = "Boot time",
            ["Sensor.battery_time_remaining"] = "Battery time remaining",
            ["Sensor.vpn_connected"] = "VPN connected",
            ["Sensor.wifi_ssid"] = "Wi-Fi SSID",
            ["Sensor.wifi_signal"] = "Wi-Fi signal strength",
            ["Sensor.logged_in_users"] = "Logged in users",
            ["Sensor.rdp_sessions"] = "RDP sessions",
            ["Sensor.bluetooth_enabled"] = "Bluetooth enabled",
            ["Sensor.windows_update_pending"] = "Windows Update pending",
            ["Sensor.event_log_errors_recent"] = "Recent event log errors",
            ["Sensor.last_shutdown_reason"] = "Last shutdown reason",
            ["Sensor.active_window"] = "Active window",
            ["Sensor.active_process"] = "Active process",
            ["Sensor.foreground_app_title"] = "Foreground app & window",
            ["Sensor.volume"] = "Volume",
            ["Sensor.muted"] = "Muted",
            ["Sensor.monitor_power_state"] = "Monitor power state",
            ["Sensor.active_display"] = "Active displays",
            ["Sensor.idle_time_seconds"] = "Idle time",
            ["Sensor.session_locked"] = "Session locked",
            ["Sensor.user_present"] = "User present",
            ["Sensor.clipboard_text_available"] = "Clipboard text available",
            ["Sensor.audio_output_device"] = "Audio output device",
            ["Sensor.microphone_muted"] = "Microphone muted",

            // Custom sensor types
            ["SensorType.process_running"] = "Process running",
            ["SensorType.service_status"] = "Service status",
            ["SensorType.disk_free"] = "Disk free space",
            ["SensorType.built_in_attribute"] = "Built-in attribute",
            ["SensorType.command"] = "Command (program)",
            ["SensorType.command_powershell"] = "Command (PowerShell)",
            ["SensorType.command_pwsh"] = "Command (PowerShell 7)",
    };
}
